config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/masters', as: 'rails_admin'

  root :to => "sessions#new"
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]

  resources :products
  get '/my-account' => 'my_account#show'
  get '/pos-invoices/get-voucher-sequences' => 'pos_invoices#get_voucher_sequences'

  get '/inventory-out-vouchers/get-voucher-sequences' => 'inventory_out_vouchers#get_voucher_sequences'
  get '/inventory-out-vouchers/get-business-entities' => 'inventory_out_vouchers#get_business_entities'

  get '/inventory-in-vouchers/get-voucher-sequences' => 'inventory_in_vouchers#get_voucher_sequences'
  get '/inventory-in-vouchers/get-business-entities' => 'inventory_in_vouchers#get_business_entities'
  get '/inventory-internal-transfer-vouchers/get-voucher-sequences' => 'inventory_internal_transfer_vouchers#get_voucher_sequences'
  get '/inventory-internal-transfer-vouchers/get-entity-locations' => 'inventory_internal_transfer_vouchers#get_entity_locations'

  get '/inventory-transactions/summary-report' => 'inventory_txn_reports#index'

  get '/pos-invoice-payments' => 'pos_invoices#payment'

  resources :pos_invoices, path: 'pos-invoices'
  get 'pos-invoices-list-with-payment' => 'pos_invoices_reports#pos_invoices_list_with_payment'
  get 'pos-invoices-line-items' => 'pos_invoices_reports#pos_invoice_line_items'
  resources :inventory_out_vouchers, path: 'inventory-out-vouchers'
  resources :inventory_in_vouchers, path: 'inventory-in-vouchers'
  resources :inventory_internal_transfer_vouchers, path: 'inventory-internal-transfer-vouchers'
  get 'inventory-internal-transfer-vouchers-line-items' => 'inventory_txn_vouchers_reports#inventory_internal_transfer_vouchers_line_items'
  resources :journal_vouchers, path: 'journal-vouchers'

  resources :users

  get '/sales-report' => 'reports#sales'
  get '/payment-collection' => 'reports#payment_collection'
  get '/stock-summary' => 'inventory_reports#stock_summary'
  get '/invoices-pending' => 'invoices_vouchers#pending_list'

  resources :states
  resources :voucher_sequences, path: 'voucher-sequences', except: :show

  get '/total-sales-summary'=>'total_sales_summary#show'
  get '/total-sales-summary-report'=>'total_sales_summary#constructdatatable'
  get '/ping' => 'ping#show'

end

app/models/inventory_in_voucher.rb
class InventoryInVoucher < InventoryTxn
  def process_calculations
    VoucherCalculations.new({voucher: self, quantity_field: 'quantity_in'}).process_totals
    errors.add(:base, 'No products added! Total amount should be more than 0') and return false if self.total_amount < 1
  end

  def mandatory_values_check(attributed)
    if attributed['product_id'].blank? || attributed['quantity_in'].to_i < 1
      # handle new records with invalid data
      return true if attributed['id'].blank?

      # handle existing records with invalid data
      attributed['_destroy'] = true if attributed['id'].present?
    end
    false
  end

  def consolidate_line_items_on_product
    VoucherConsolidateLineItems.new({voucher: self, association_name: 'line_items', attrib_id: 'product_id', consolidate: 'quantity_in'}).consolidate_with_same_attribute
  end
end

app/controllers/inventory_in_vouchers_controller.rb
class InventoryInVouchersController < ApplicationController
  power :inventory_in_vouchers, map:
    {
    [:edit, :update, :get_voucher_sequences, :get_business_entities]=> :updatable_inventory_in_vouchers,
    [:new, :create, :get_voucher_sequences, :get_business_entities] => :creatable_inventory_in_vouchers,
    [:index, :show] => :inventory_in_vouchers_view,
    [:destroy] => :destroyable_inventory_in_vouchers
    }, as: :inventory_in_voucher_scope
  include VoucherSequenceable
  include VoucherExtensible
  before_action :set_inventory_in_voucher, only: [:edit, :update, :destroy]

  def index
    @inventory_in_vouchers = inventory_in_voucher_scope.includes(:created_by, :secondary_entity, [primary_location: :business_entity]).order("number DESC")

    respond_to do |format|
      format.html
      format.csv { send_data @inventory_in_vouchers.to_csv, filename: "purchase_transactions_complete_#{Time.zone.now.in_time_zone.strftime('%Y%m%d')}.csv" }
      format.xls { send_data @inventory_in_vouchers.to_csv(col_sep: "\t"), filename: "purchase_transactions_complete_#{Time.zone.now.in_time_zone.strftime('%Y%m%d')}.xls" }
    end
  end

  def show
    @inventory_in_voucher = inventory_in_voucher_scope.includes(:created_by).find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @inventory_in_voucher = InventoryInVoucher.new({voucher_date: Time.zone.now.in_time_zone.strftime('%d/%m/%Y')})
    initialize_form
  end

  def edit
    initialize_form
  end

  def create
    @inventory_in_voucher = InventoryInVoucher.new(inventory_in_voucher_params.merge!(current_user_id: current_user.id))

    respond_to do |format|
      if @inventory_in_voucher.save
        initialize_form
        format.html { redirect_to @inventory_in_voucher, flash: { success: 'Inventory In Voucher was created successfully.'} }
        format.json { render :show, status: :created, location: @inventory_in_voucher }
      else
        initialize_form
        format.html { render :new }
        format.json { render json: @inventory_in_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inventory_in_voucher.update(inventory_in_voucher_params.merge!(current_user_id: current_user.id))
        format.html { redirect_to @inventory_in_voucher, flash: {success: 'Inventory In Voucher was updated successfully.'}}
        format.json { render :show, status: :ok, location: @inventory_in_voucher }
      else
        initialize_form
        format.html { render :edit }
        format.json { render json: @inventory_in_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory_in_voucher.destroy
    respond_to do |format|
      format.html { redirect_to inventory_in_vouchers_url, notice: 'Inventory In Voucher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def inventory_in_voucher_params
      params.require(:inventory_in_voucher).permit(:created_by_id, :remarks,
          :tax_amount, :total_amount, :voucher_date, :ref_number, :status, :voucher_sequence_id,
          :goods_value, :primary_location_id, :address, :tax_details, :secondary_entity_id,
          line_items_attributes: [:id, :product_id, :quantity_in, :price, :amount, :tax_rate,
            :_destroy]
        )
      #:tax_amount will be calculated on server-side and not accepted as params
    end

    def set_inventory_in_voucher
      @inventory_in_voucher = inventory_in_voucher_scope.includes(:line_items).find(params[:id])
    end

    def populate_products
      @products ||= Product.includes([:language, :category]).active.order(:sku).load
    end

    def build_child_line_items
      rec_count = @inventory_in_voucher.line_items.size
      if rec_count < 4
        (25 - rec_count).times { @inventory_in_voucher.line_items.build }
      else
        5.times { @inventory_in_voucher.line_items.build }
      end
    end

    def initialize_form
      populate_products
      build_child_line_items
    end
end

app/views/inventory_in_vouchers/_form.html.erb
<%= form_for @inventory_in_voucher do |f| %>
<%= render 'layouts/error_messages', object: f.object %>
  <div class='row'>
    <div class="col-md-10 text-center">
      <div class='col-md-2 form-group text-center'>
        <%= f.label :voucher_date, 'Date' %>
        <%= f.text_field :voucher_date, value: (f.object.voucher_date.strftime('%d/%m/%Y') if f.object.voucher_date), class: 'datetimepicker text-center form-control', required: 'true', type: 'date' %>
      </div>
      <div class='col-md-3'>
        <div class='form-group text-center'>
          <div id='secondary_business_entity_div' class='form-group text-center'>
            <%= label nil, 'Vendor' %>
            <%= f.collection_select :secondary_entity_id, BusinessEntity.anc_with_reserved_inventory_in_vouchers(f.object.secondary_entity_id), :id, :alias_name,
                    { include_blank: true },
                    { class: 'form-control selectme', id: 'secondary_business_entity' } %>
          </div>
        </div>
        <div class='form-group text-center'>
          <%= label nil, 'Consignee :: Location' %>
          <%= f.collection_select :primary_location_id, BusinessEntityLocation.includes(:business_entity).own_locations.active_n_current(@inventory_in_voucher.primary_location_id), :id, :entity_name_with_location, { include_blank: true },
            { class: 'form-control selectme', id: 'primary_location' } %>
        </div>
      </div>
      <div class='col-md-2'>
        <div class='form-group text-center'>
          <%= f.label :voucher_sequence_id, 'Sequence' %>
          <%= hidden_field  '', 'voucher_sequence', value: f.object.voucher_sequence_id %>
          <%= f.collection_select :voucher_sequence_id, VoucherSequence.anc_inventory_in_vouchers(f.object.voucher_sequence_id), :id, :number_prefix, { include_blank: true }, { class: 'form-control selectme', id: 'voucher_sequence' } %>
        </div>
        <div class='form-group text-center'>
          <div class='form-group text-center'>
            <%= f.label :number %>
            <%= f.text_field :number, value: ((f.object.number == 0 || f.object.number.blank?) ? 'New' : f.object.number), class: 'form-control text-center', disabled: true %>
          </div>
        </div>
      </div>
      <div class='col-md-2'>
        <div class='form-group text-center'>
          <%= label_tag '# of products' %>
          <%= label_tag '0', nil, class: 'form-control text-center products_count', disabled: true %>
        </div>
        <div class='form-group text-center'>
          <%= f.label :amount %>
          <%= label_tag '0.00', nil, id: 'voucher_amount', class: 'form-control text-center', disabled: true %>
        </div>
      </div>
      <div class="col-md-3 form-group" style='margin-top:20px;'>
        <%= f.text_area :remarks, class: 'form-control', rows: 5, type: 'text',
                        placeholder: 'Remarks', tabindex: '-1' %>
      </div>
    </div>
    <div class="col-md-2 text-center">
      <div class="text-center">
        <div class='form-group text-center'>
          <%= f.submit "Save", class: 'btn btn-primary btn-block', id: 'save_button' %>
        </div>
        <div class='form-group text-center'>
          <%= link_to 'List of invoices', inventory_in_vouchers_url, :class => 'btn btn-primary btn-block' %>
        </div>
        <div class='form-group text-center'>
          <%= link_to 'Delete', f.object, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-block' if current_power.destroyable_inventory_in_vouchers? && f.object.persisted? %>
        </div>
      </div>
    </div>
  </div>

  <hr style='margin-top:0px;margin-bottom:5px;border-color:black'>

  <%# cache [@inventory_in_voucher, "inventory_in_voucher_line_items"] do %>
    <div class="table-responsive table-striped table-hover">
      <table id='voucher_line_items' class='voucher_line_items_table'>
        <thead>
          <tr style='height:30px;'>
            <th class="col-md-2 text-center">SKU</th>
            <th class="col-md-6 text-center">Product</th>
            <th class="col-md-1 text-center">Qty</th>
            <th class="col-md-1 text-center">Rate</th>
            <th class="col-md-2 text-center">Amount</th>
          </tr>
        </thead>
        <tbody>
          <%= f.fields_for :line_items do |f_line_item| %>
            <tr class="fields">
              <td><%= select "#{f_line_item.object_name}", 'sku', @products.map { |x| [x.sku.to_i, x.id] }, {include_blank: true}, class: 'form-control selectme text-center voucher_line_item_sku' %></td>
              <td><%= f_line_item.collection_select :product_id, @products, :id, :voucher_label,
                        { include_blank: true }, { class: 'form-control selectme voucher_line_item_product' } %></td>
              <td><%= f_line_item.text_field :quantity_in, class: 'form-control text-center voucher_line_item_quantity', type: 'number', min: 0 %></td>
              <td><%= f_line_item.text_field :price, class: 'form-control text-center voucher_line_item_rate', tabindex: '-1', min: 0, readonly: true %></td>
              <td style='padding-right:0px;'>
                <%= f_line_item.text_field :amount, class: 'form-control text-center voucher_line_item_amount', tabindex: '-1', min: 0, readonly: true, style: 'width:80%;float:left;' %>
                <%= link_to "", '#', class: "voucher_line_item_remove fa fa-trash-o fa-lg fa-td", tabindex: '-1' %>
                <%= f_line_item.hidden_field :_destroy, size: '5x5', class: 'line_item_destroy' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <%# end %>
<% end %>

app/views/inventory_in_vouchers/edit.html.erb
<% provide(:title, 'Edit Inventory In Voucher') %>
<%= render 'form' %>

app/views/inventory_in_vouchers/index.html.erb
<% provide(:title, 'InventoryIn Vouchers listing') %>
<%= link_to 'New InventoryIn Voucher', new_inventory_in_voucher_path, class: 'pull-right' %>
<div class="display responsive no-wrap voucher_line_items">
  <table id='voucher_line_items' class='DataTable DataTable-line-items'>
    <thead>
      <tr>
        <th class='col-md-1 text-center'>Date</th>
        <th class='col-md-1 text-center'>Invoice #</th>
        <th class='col-md-1 text-center'>Vendor/Source</th>
        <th class='col-md-3 text-center'>Entity Location</th>
        <th class='col-md-1 text-center'>Amount</th>
        <th class='col-md-2 text-center'>Remarks</th>
        <th class='col-md-1 text-center'>Created by</th>
        <th class='col-md-1 text-center'>Operations</th>
      </tr>
    </thead>
    <tbody>
      <% @inventory_in_vouchers.each do |inventory_in_voucher| %>
        <tr>
          <td class='text-center'><%= inventory_in_voucher.voucher_date.strftime('%d/%m/%Y') %></td>
          <td class='text-center'><%= inventory_in_voucher.voucher_number %></td>
          <td class='text-center'><%= inventory_in_voucher.secondary_entity_alias_name %></td>
          <td class='text-center'><%= inventory_in_voucher.primary_entity_name_with_location %></td>
          <td class='text-center'><%= inventory_in_voucher.total_amount %></td>
          <td><%= inventory_in_voucher.remarks %></td>
          <td class='text-center'><%= inventory_in_voucher.created_by.custom_object_label %></td>
          <td class='text-center'>
            <%= link_to 'View', inventory_in_voucher %> | <%= link_to 'Edit', edit_inventory_in_voucher_path(inventory_in_voucher) %> | <%= link_to 'Delete', inventory_in_voucher, method: :delete, data: { confirm: 'Are you sure?' } if current_power.destroyable_inventory_in_vouchers? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/inventory_in_vouchers/index.xls.erb
<table border='1'>
  <thead>
    <tr>
      <th>Date</th>
      <th>Invoice #</th>
      <th>SKU</th>
      <th>Product Name</th>
      <th>Cat. Code</th>
      <th>Lang. Code</th>
      <th>Qty</th>
      <th>Rate</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_in_vouchers.rows_for_export.each do |details| %>
      <tr>
        <td><%= details[0] %></td>
        <td><%= details[1] %></td>
        <td><%= details[2] %></td>
        <td><%= details[3] %></td>
        <td><%= details[4] %></td>
        <td><%= details[5] %></td>
        <td><%= details[6] %></td>
        <td><%= details[7] %></td>
        <td><%= details[8] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/inventory_in_vouchers/new.html.erb
<% provide(:title, 'New Inventory In Voucher') %>
<%= render 'form' %>

app/views/inventory_in_vouchers/show.html.erb
<p>
  <strong>Created by user:</strong>
  <%= @inventory_in_voucher.created_by.custom_object_label %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @inventory_in_voucher.remarks %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @inventory_in_voucher.total_amount %>
</p>

<p>
  <strong>Number:</strong>
  <%= @inventory_in_voucher.voucher_number %>
</p>

<%= link_to 'New Invoice', new_inventory_in_voucher_url, id: 'open_new_invoice' %> | <%= link_to 'Edit', edit_inventory_in_voucher_path(@inventory_in_voucher) %> | <%= link_to 'Invoices Listing', inventory_in_vouchers_path %> | <%= link_to 'Delete', @inventory_in_voucher, method: :delete, data: { confirm: 'Are you sure?' } if current_power.destroyable_inventory_in_vouchers? %>