config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/masters', as: 'rails_admin'

  root :to => "sessions#new"
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]

  resources :products
  get '/my-account' => 'my_account#show'
  get '/pos-invoices/get-voucher-sequences' => 'pos_invoices#get_voucher_sequences'

  get '/inventory-out-vouchers/get-voucher-sequences' => 'inventory_out_vouchers#get_voucher_sequences'
  get '/inventory-out-vouchers/get-business-entities' => 'inventory_out_vouchers#get_business_entities'

  get '/inventory-in-vouchers/get-voucher-sequences' => 'inventory_in_vouchers#get_voucher_sequences'
  get '/inventory-in-vouchers/get-business-entities' => 'inventory_in_vouchers#get_business_entities'
  get '/inventory-internal-transfer-vouchers/get-voucher-sequences' => 'inventory_internal_transfer_vouchers#get_voucher_sequences'
  get '/inventory-internal-transfer-vouchers/get-entity-locations' => 'inventory_internal_transfer_vouchers#get_entity_locations'

  get '/inventory-transactions/summary-report' => 'inventory_txn_reports#index'

  get '/pos-invoice-payments' => 'pos_invoices#payment'

  resources :pos_invoices, path: 'pos-invoices'
  get 'pos-invoices-list-with-payment' => 'pos_invoices_reports#pos_invoices_list_with_payment'
  get 'pos-invoices-line-items' => 'pos_invoices_reports#pos_invoice_line_items'
  resources :inventory_out_vouchers, path: 'inventory-out-vouchers'
  resources :inventory_in_vouchers, path: 'inventory-in-vouchers'
  resources :inventory_internal_transfer_vouchers, path: 'inventory-internal-transfer-vouchers'
  get 'inventory-internal-transfer-vouchers-line-items' => 'inventory_txn_vouchers_reports#inventory_internal_transfer_vouchers_line_items'
  resources :journal_vouchers, path: 'journal-vouchers'

  resources :users

  get '/sales-report' => 'reports#sales'
  get '/payment-collection' => 'reports#payment_collection'
  get '/stock-summary' => 'inventory_reports#stock_summary'
  get '/invoices-pending' => 'invoices_vouchers#pending_list'

  resources :states
  resources :voucher_sequences, path: 'voucher-sequences', except: :show

  get '/total-sales-summary'=>'total_sales_summary#show'
  get '/total-sales-summary-report'=>'total_sales_summary#constructdatatable'
  get '/ping' => 'ping#show'

end

app/models/state.rb
class State < MyActiveRecord
  belongs_to :region, inverse_of: :states
  has_many :cities, inverse_of: :state, dependent: :restrict_with_exception
  has_many :state_category_tax_rates, inverse_of: :state, dependent: :restrict_with_exception

  validates :name, presence: true, length: { in: 3..50 }
  validates :code, presence: true, length: { in: 1..3 }, uniqueness: { case_sensitive: false }
  validates :region_id, presence: true, uniqueness: { scope: :name, case_sensitive: false }
  validates :active, inclusion: { in: [true, false] }

  before_validation :code_upcase

  delegate :name, to: :region, prefix: true, allow_nil: true

  default_scope -> { where reserved: false }

  def code_upcase
    self.code = self.code.upcase if self.code.present?
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  power :states, as: :state_scope
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  def index
    @states = state_scope
  end

  def show
  end

  def new
    @state = State.new
  end

  def edit
  end

  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_state
      @state = state_scope.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:name, :region_id, :code, :active)
    end
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :region_id %><br>
    <%= f.text_field :region_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.text_field :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<% provide(:title, 'States listing') %>

<div class="display responsive no-wrap voucher_line_items">
  <table id='voucher_line_items' class='DataTable DataTable-line-items'>
    <thead>
      <tr>
        <th class='col-md-3 text-center'>Name</th>
        <th class='col-md-2 text-center'>Region</th>
        <th class='col-md-2 text-center'>Code</th>
        <th class='col-md-1 text-center'>Active</th>
        <th class='col-md-2 text-center'>Count of Tax Slabs</th>
        <th class='col-md-2 text-center'>Operations</th>
      </tr>
    </thead>

    <tbody>
      <% @states.each do |state| %>
        <tr>
          <td><%= state.name %></td>
          <td class='text-center'><%= state.region_name %></td>
          <td class='text-center'><%= state.code %></td>
          <td class='text-center'><%= state.active %></td>
          <td class='text-center'></td>
          <td class='text-center'><%= link_to 'Show', state %> | <%= link_to 'Edit', edit_state_path(state) %></td>
          <!-- <td><%#= link_to 'Delete', state, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @state.region_id %>
</p>

<p>
  <strong>Code:</strong>
  <%= @state.code %>
</p>

<p>
  <strong>Active:</strong>
  <%= @state.active %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>